#!/bin/bash

shopt -s nullglob dotglob extglob

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

# Options
cmd=status
verbosity=0
scan=/opt
flavors=('' Canary PTB)
discord=
modules=
bd_repo='https://github.com/rauenzi/BetterDiscordApp'
bd_repo_branch=stable16
bd=
copy_bd=
global_asar=

# Variables
flavor=
core=
xdg_config="${XDG_CONFIG_DIR:-$HOME/.config}"
data="${XDG_DATA_HOME:-$HOME/.local/share}/betterdiscordctl"

verbose() {
  if (( verbosity >= $1 )); then
    shift
    printf '%s\n' "$1"
  fi
}

show_help() {
  printf 'Usage: %s [OPTION...] [COMMAND]\n\n' "${0##*/}"
  cat << EOF
Options:
  -h, --help: Show this help
  -v, --verbose: Increase verbosity
  -s, --scan=DIRECTORY: Directory to scan for Discord installations
                        (default '/opt')
  -f, --flavors=FLAVORS: Comma-separated list of Discord flavors
                         (default ',Canary,PTB')
  -d, --discord=DIRECTORY: Use specified Discord directory (requires --modules)
  -m, --modules=DIRECTORY: Use specified Discord modules directory
  -r, --bd-repo=REPOSITORY: Use specified Git repository for BD installation
  --bd-repo-branch=BRANCH: Use specified Git branch (default 'stable16')
  -b, --betterdiscord=DIRECTORY: Use specified BetterDiscord directory
  -c, --copy-bd: Copy BetterDiscord directory instead of symlinking
  --global-asar: Use PATH's asar instead of a local installation

Commands:
  status (default): Show information about the current Discord patch state.
  install: Install BetterDiscord.
  update: Update BetterDiscord.
  uninstall: Uninstall BetterDiscord.
EOF
}

die_non_empty() {
  die "ERROR: \"$1\" requires a non-empty option argument."
}

while :; do
  case $1 in
    status|install|update|uninstall)
      cmd=$1
      ;;
    -h|-\?|--help)
      show_help; exit
      ;;
    -v|--verbose)
      ((++verbosity))
      ;;
    -s|--scan)
      if [ "$2" ]; then scan=$2; shift
      else die_non_empty '--scan'; fi
      ;;
    --scan=?*)
      scan=${1#*=}
      ;;
    --scan=)
      die_non_empty '--scan'
      ;;
    -f|--flavors)
      if [ "$2" ]; then
        readarray -td, flavors <<<"$2,"; unset 'flavors[-1]'
        shift
      else die_non_empty '--flavors'; fi
      ;;
    --flavors=?*)
      readarray -td, flavors <<<"${1#*=},"; unset 'flavors[-1]'
      ;;
    --flavors=)
      die_non_empty '--flavors'
      ;;
    -d|--discord)
      if [ "$2" ]; then discord=$2; shift
      else die_non_empty '--discord'; fi
      ;;
    --discord=?*)
      discord=${1#*=}
      ;;
    --discord=)
      die_non_empty '--discord'
      ;;
    -m|--modules)
      if [ "$2" ]; then modules=$2; shift
      else die_non_empty '--modules'; fi
      ;;
    --modules=?*)
      modules=${1#*=}
      ;;
    --modules=)
      die_non_empty '--modules'
      ;;
    --bd-repo-branch)
      if [ "$2" ]; then bd_repo_branch=$2; shift
      else die_non_empty '--bd-repo-branch'; fi
      ;;
    --bd-repo-branch=?*)
      bd_repo_branch=${1#*=}
      ;;
    --bd-repo-branch=)
      die_non_empty '--bd-repo-branch'
      ;;
    -r|--bd-repo)
      if [ "$2" ]; then bd_repo=$2; shift
      else die_non_empty '--bd-repo'; fi
      ;;
    --bd-repo=?*)
      bd_repo=${1#*=}
      ;;
    --bd-repo=)
      die_non_empty '--bd-repo'
      ;;
    -b|--betterdiscord)
      if [ "$2" ]; then bd=$2; shift
      else die_non_empty '--betterdiscord'; fi
      ;;
    --betterdiscord=?*)
      bd=${1#*=}
      ;;
    --betterdiscord=)
      die_non_empty '--betterdiscord'
      ;;
    -c|--copy-bd)
      copy_bd=yes
      ;;
    --global-asar)
      global_asar=yes
      ;;
    --)
      shift
      break
      ;;
    -?*)
      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
      ;;
    *)
      break
  esac

  shift
done

[ ! -d "$data" ] && mkdir -p "$data"
[ ! -f "$data/bd_map" ] && touch "$data/bd_map"

if [ -z "$discord" ]; then
  while true; do
    for flavor in "${flavors[@]}"; do
      verbose 2 "VV: Trying flavor '$flavor'" >&2
      for discord in "$scan/discord${flavor,,}" "$scan/discord-${flavor,,}" \
                     "$scan/Discord$flavor" "$scan/Discord-$flavor"; do
        verbose 2 "VV: Checking $discord" >&2
        if [ -d "$discord" ] ; then
          verbose 2 "VV: Detected $discord" >&2
          tmp_config="$xdg_config/discord${flavor,,}"
          if [ ! -d "$tmp_config" ]; then
            printf "WARN: Config directory not found for %s (%s, %s).\n" "$flavor" "$discord" "$tmp_config" >&2
            continue 2
          fi
          verbose 1 "V: Using Discord at $discord" >&2
          if [ -z "$modules" ]; then
            modules=("$tmp_config/"+([0-9]).+([0-9]).+([0-9])"/modules")
            if ((! ${#modules[@]})); then
              die 'ERROR: Discord modules directory not found.'
            fi
            modules="${modules[0]}"
          else
            # --modules
            if [ ! -d "$modules" ]; then
              die 'ERROR: Discord modules directory not found.'
            fi
          fi
          break 3
        fi
      done
    done
    die 'ERROR: Discord installation not found.'
    break
  done
else
  # --discord and --modules 
  if [ -z "$modules" ]; then
    die 'ERROR: "--discord" requires "--modules" to also be set.'
  fi
  if [ ! -d "$discord" ]; then
    'ERROR: Discord installation not found.'
  fi
  if [ ! -d "$modules" ]; then
    'ERROR: Discord modules directory not found.'
  fi
fi
core="$modules/discord_desktop_core"

# Commands

bdc_status() {
  app_patched=no
  core_patched=no
  linked_dir=no
  linked_repo=no
  if [ -d "$discord/resources/app" ]; then
    app_patched=yes
  fi
  if [ -d "$core/core" ]; then
    core_patched=yes
    if [ -h "$core/core/node_modules/betterdiscord" ]; then
      linked_dir="$(readlink "$core/core/node_modules/betterdiscord")"
      if [ -d "$core/core/node_modules/betterdiscord" ]; then
        pushd "$core/core/node_modules/betterdiscord" >/dev/null
        linked_repo="$(git remote get-url origin 2>/dev/null || printf 'no\n')"
        popd >/dev/null
      else
        linked_dir="(broken link) $linked_dir"
      fi
    fi
  fi

  printf 'Discord: %s
Modules: %s
App patched: %s
Core patched: %s
Linked core directory: %s
Linked core repository: %s\n' \
    "$discord" "$modules" "$app_patched" "$core_patched" "$linked_dir" "$linked_repo"
}

bdc_install() {
  if [ -d "$core/core" ]; then
    printf 'Already installed.\n' >&2
    exit 1
  fi

  bd_patch

  if [ ! "$bd" ]; then
    printf 'Cloning %s...\n' "$bd_repo" >&2
    bd="$data/bd/$(bd_map_add "$discord" "$bd_repo")"
    if [ ! -d "$bd" ]; then
      git clone "$bd_repo" -b stable16 --single-branch "$bd"
    fi
  fi

  if [ "$copy_bd" ]; then
    verbose 1 'V: Copying core loader...' >&2
    cp -r "$bd" "$core/core/node_modules/betterdiscord"
  else
    verbose 1 'V: Linking core loader...' >&2
    ln -s "$bd" "$core/core/node_modules/betterdiscord"
  fi

  printf 'Installed. (Restart Discord if necessary.)\n' >&2
}

bdc_update() {
  if [ ! -d "$core/core" ]; then
    printf 'Not installed.\n' >&2
    exit 1
  fi

  if [ ! -d "$core/core/node_modules/betterdiscord" ]; then
    if [ -h "$core/core/node_modules/betterdiscord" ]; then
      die 'ERROR: Core BetterDiscord symbolic link is broken.'
    else
      die 'ERROR: Core BetterDiscord location is not a directory.'
    fi
  fi
  pushd "$core/core/node_modules/betterdiscord" >/dev/null
  if git rev-parse --is-inside-work-tree > /dev/null 2>/dev/null; then
    printf 'Updating Git repository...\n' >&2
    git fetch origin
    git reset --hard "origin/$bd_repo_branch"
  else
    printf 'No Git repository found.\n' >&2
  fi
  popd >/dev/null
}

bdc_uninstall() {
  if [ ! -e "$core/core" ]; then
    printf 'Not installed.\n' >&2
    exit 1
  fi

  printf "Killing Discord...\n" >&2
  killall -SIGKILL -qwr '^[dD]iscord'

  bd_unpatch

  # Remove managed BD repo if applicable
  bd_n=$(bd_map_get_dir "$discord" | bd_map_entry_n)
  bd_map_remove "$discord"
  if [ -z "$(bd_map_get_n $bd_n)" ]; then
    rm -rf "$data/bd/$bd_n"
  fi

  # Clean up legacy cruft
  if [ -d "$discord/resources/app" ]; then
    rm -r "$discord/resources/app"
  fi

  printf 'Uninstalled.\n' >&2
}

# Implementation functions

bdc_asar() {
  if [ "$global_asar" ]; then
    asar "$@"
  else
    if mkdir "$data/asar" 2>/dev/null; then
      pushd "$data/asar" >/dev/null
      printf '{"devDependencies":{"asar": "*"}}\n' > package.json
      printf 'Installing asar...\n' >&2
      npm install
    else
      pushd "$data/asar" >/dev/null
      printf 'Updating asar...\n' >&2
      npm update
    fi
    popd >/dev/null
    "$data/asar/node_modules/asar/bin/asar.js" "$@"
  fi
}

bd_patch() {
  verbose 1 'V: Unpacking core asar...' >&2
  bdc_asar e "$core/core.asar" "$core/core"
  sed "s/core\.asar'/core'/g" -i "$core/index.js"

  verbose 1 'V: Patching core entry...' >&2
  sed \
    -e "/var *_url *=/ a var _betterDiscord = require('betterdiscord'); var _betterDiscord2;" \
    -e "/mainWindow *= *new/ a _betterDiscord2 = new _betterDiscord.BetterDiscord(mainWindow);" \
    -i "$core/core/app/mainScreen.js"
}

bd_unpatch() {
  verbose 1 "V: Removing core folder from modules..." >&2
  sed "s/core'/core.asar'/g" -i "$core/index.js"
  rm -rf "$core/core"
}

bd_map_entry_n() {
  sed 's/^.*\t\t.*\t\(.*\)$/\1/' "$@"
}

bd_map_fresh() {
  verbose 1 "V: Generating fresh bd_map number..." >&2
  bd_map_entry_n "$data/bd_map" | sort | awk 'BEGIN {max=-1} NF != 0 {if ($1>max+1) {exit}; max=$1} END {print max+1}'
}

bd_map_add() {
  entry="$(bd_map_get_repo "$2")"
  if [ "$entry" ]; then
    num=$(head -n1 <<< "$entry" | bd_map_entry_n)
  else
    num=$(bd_map_fresh)
  fi
  printf '%s\t\t%s\t%s\n' "$1" "$2" $num >> "$data/bd_map"
  printf '%s\n' $num
}

bd_map_get_dir() {
  grep -F "$1"$'\t\t' "$data/bd_map"
}

bd_map_get_repo() {
  grep -F $'\t\t'"$1"$'\t' "$data/bd_map"
}

bd_map_get_n() {
  grep $'\t'"$1\$" "$data/bd_map"
}

bd_map_remove() {
  grep -vF "$1"$'\t\t' "$data/bd_map" > "$data/bd_map.temp"
  mv "$data/bd_map.temp" "$data/bd_map"
}

# Run command

case "$cmd" in
  status)
    bdc_status
    ;;
  install)
    bdc_install
    ;;
  update)
    bdc_update
    ;;
  uninstall)
    bdc_uninstall
    ;;
  *)
    die "ERROR: Unknown command: $cmd"
    ;;
esac
